[urls]
noaa_rss_feed_url = "https://www.spc.noaa.gov/products/spcrss.xml"
discord_webhook_url = "https://discord.com/api/webhooks/verylongkey"

[storage]
seen_alerts_cache = "./storage/seen_alerts.json"

[filters]
title_must_not_include = ["No watches are valid", "Fire"]
summary_must_not_include = ["HAS NOT BEEN ISSUED YET"]

# Summary must include only one of the following terms.
summary_must_include = ["Nebraska", "Iowa", "Oklahoma"]
